### ISSUE TITLE
Consider using the new `EventCounter` mechanisms in .net core 3

### ISSUE THREAD

**Issue by baronfel** [djluck/prometheus-net.DotNetRuntime#15]
There's an article [here](https://medium.com/criteo-labs/net-core-counters-internals-how-to-integrate-counters-in-your-monitoring-pipeline-5354cd61b42e) detailing the use of new `EventCounter` in the .net 3.0 runtime. These are supposed to have a performance improvement vs the EventListener-backed stuff, do you think there's any place for them here?

**Comment by djluck** [comment]
It's certainly worth a look at some point. One thing that jumps out is that these `EventCounter`s might not expose detailed timing information, i.e. they only expose the total or average rate of an event. Currently this library can measure certain events (such as GC timings) as distributions, giving greater insight into how your application performs. Although I need to perform a more thorough accounting of this, I don't think the CPU/ memory overhead of listening to events is that high currently.

**Comment by baronfel** [comment]
The first thing that came to mind for me is the Microsoft is suggesting that uses write application-level counters using this new set of types, so would it make sense to provide something similar to the StatsCollector/EventListener types you have here, but for `EventCounters` instead of the ETW events?

**Comment by djluck** [comment]
It will definitely improve performance for certain events but certain information will be lost. 

For example, take the `dotnet_gc_allocated_bytes_total` metric- this is currently populated by listening to the [GCAllocationTick_V2 event](https://docs.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events#gcallocationtick_v2_event). We could move towards just listening to the new `alloc-rate` counter which will improve performance (GCAllocationTick_V2 is fired every 100KB of objects allocated which for busy apps, can see thousands of events raised a second) but we will loose useful information as the counter can't tell you if the allocation was on the small or large object heap. 

Almost every attempt to replace event-based instrumentation with counter-based instrumentation will probably involve a similar tradeoff so accounting for this will take some time. Some users may prefer the smallest amount of possible overhead while others may rely on the greater detail.

**Comment by rynowak** [comment]
We'd be happy to discuss more if you have if you have feedback or concerns about what the built-in event counters are doing. @noahfalk @shirhatti

**Comment by djluck** [comment]
Hey @rynowak, I think the counters are good step in the right direction it's just that they don't offer the same level of detail as the events do. I'd like to move over to a counter-based approach as this will reduce performance overhead for sure. Some things that come to mind that would support this library are:
- Percentile/ histogram based statistics. It seems that counters can only offer current/ total/ average at the moment. More advanced statistics would be great
- More counters. This library measures things that can't currently be collected via Counters (e.g. ThreadPool scheduling latency, LOH/SOH alloc rate, GC timings)

**Comment by noahfalk** [comment]
@dijluck - Thanks for the feedback!

I fully agree with you that counters are best thought of a complement to the events rather than a replacement for them. Counters aim to serve a low-overhead/low-information scenario and more detailed events move up that scale providing more information in exchange for potentially additional overhead. I don't expect the counters will ever provide equivalent info as the events, but we are glad to get feedback and keep adjusting trying to find the best sweet spot.

One question I'd love to get your opinion on - I can see two potential ways of approaching the Percentile/histogram based stats:
1) The runtime provides a richer set of built-in analysis primitives such as histograms, percentiles, or other types of statistics about distributions. These things tend to have various additional parameters such as the size of buckets, sampling rates, the percentile cut-off for percentiles, perhaps additional variables for a multi-variate distribution? These could either have hard-coded defaults or input formats of varying complexity/flexibility for the data consumers to describe the measurement configuration they want.
2) The runtime provides raw data efficiently and lets a library consuming that data analyze it into whatever form it wishes. For example the GC has GC.GetTotalAllocatedBytes() which is the basis for the alloc-rate counter. A library could call that API directly and then slice and dice those numbers however it wished, such as putting the samples into a histogram. For cases where the underlying data you'd want to analyze isn't exposed we could add APIs to get it exposed. 

My guess is that option (1) is easier if the runtime supports exactly the analysis you wanted, but like today you can't convert one type of analysis into another type if you wanted something a little different. Option (2) makes it more likely that you can get the exact analysis you want, but a bit of extra coding might be involved to do the calculations you wanted to have.

**Comment by djluck** [comment]
So I think my requirements of percentile/ histogram-based counters _only_ apply if counters that measure a distribution (e.g. GC durations, thread pool scheduling latency, thread pool execution time, size of JIT'd methods, etc.) come into play. 
I think that the only option would be for the `Counter` type to expose these kind of statistics- otherwise any attempt at pulling the raw data is effectively events, right?

**Comment by djluck** [comment]
Hey @noahfalk, sorry for the late reply.

In my incredibly hasty benchmarking, enabling events had about a 15% overhead. The benchmarking setup was:

- i4790k 8 core CPU
- ASP.NET core 3.0 preview8 app
- `bombardier` hitting an "empty' MVC endpoint, set to 250 connections
- When all event generation was disabled, ~59K requests processed/ sec
- When `prometheus-net.DotNetRuntime` events were enabled, ~51K requests processed/ sec (processing of events by `prometheus-net.DotNetRuntime` was disabled, only overhead was publishing and consuming events via an empty method in an `EventListener`-derived class)

Now, this is somewhat of a meaningless benchmark- the MVC app wasn't doing anything useful and in my experience, no app will ever maintain the kind of throughput numbers that TechEmpower put out (most code is written to meet a business need and rarely is high performance a critical business need). But it does show that for event-heavy apps, event generation costs can pile up. 

I still think that this can be an acceptable loss of performance for most apps but I'd always like to keep the impact as low as possible and to do this, I think `EventCounter` will be the way forward.

**Comment by noahfalk** [comment]
@djluck, no worries, I really appreciate you taking the time to poke around and give us the feedback!

> I still think that this can be an acceptable loss of performance for most apps but I'd always like to keep the impact as low as possible

Certainly. Do you have a sense what level of overhead is low enough that performance would no longer be a top priority and instead you'd go after other goals such as richer data? In particular we don't have EventCounter based histograms right now and any possible way of doing it will need to run some extra code somewhere which will have a perf cost. Do you have a threshold in mind where if the histograms cost less than X% you would turn them on, but over that you wouldn't use them?

**Comment by djluck** [comment]
Hey @noahfalk,

I think the current overhead would be acceptable for the majority of apps. While personally I don't don't use this library anywhere (currently), I did use similar concept based on ETW events to monitor .NET framework apps in production. For me, the tradeoff of less throughput for greater insight into potential missteps of applications was well worth it.

Having said that, a 10-15% throughput hit would probably be off putting to some users. Personally I'd like to get it as low as possible over time, mainly because this cost multiplied over many production hosts will stack up and secondly that this problem space is just interesting to me. I think event counters could offer a good solution here (but I also have some ideas about disabling and enabling the event sources intermittently to reduce events generated + consumed).

**Comment by noahfalk** [comment]
Thanks @djluck! Based on that I'm going to treat ~15% as the threshold of viability where a moderate number of customers might choose to enable the additional telemetry, but I'd expect progressively more customers would be happier as the costs descend down to the low single digits.

FWIW, last time I benchmarked I think I was getting ~100k EventListener events per second on a midrange desktop machine, so any events you want to enable that are ~1k events per second will probably be ~1% overhead range, all the way up to ~10k events/sec which might start to push up against the 10-15% limits. Using that rough rule of thumb I would predict that listening to GC events should be a non-issue for you, but listening to a few events per threadpool work item or other similarly frequent occurence might be trouble at the current level of event performance. 

I also opened some issues ([here](https://github.com/dotnet/diagnostics/issues/470) and [here](https://github.com/dotnet/diagnostics/issues/469)) that link back to your original feedback above. If you didn't mind I might have some other questions for you in the future, but I'll get out of your hair for now unless there was more you wanted to chat about ; ) If you've ever got questions or requests feel free to reach out to us on the [diagnostics repo](https://github.com/dotnet/diagnostics). Thanks!

**Comment by djluck** [comment]
Hey @noahfalk,

Thanks for creating those issues. I'm only too happy to answer any questions in the future but for now, I'll just watch what happens with those issues.

Regarding the benchmarking, I don't have any solid figures to hand for the numbers of events generated per second but I would imagine it was in the ~10-100K range. From memory:
- Thread pool queue/dequeue was very heavy (at least 1 pair of events per request processed)
- GC events were also heavy (listening at the `Verbose` level means you not only get alloc events but some other noisy events). Using the allocation counter here could greatly help.

**Comment by sywhang** [comment]
Hi @djluck,

I'm looking into what it'd take to implement some of the counters you mentioned in this thread. Could you please tell me a little bit more about what you mean by "GC timings" here?

**Comment by djluck** [comment]
Hey @sywhang,

Sure thing. So what I do in the this project is to capture the duration of every GC that occurs and generate a histogram of the duration in seconds, with one histogram per unique combination of generation (0-2) and type (concurrent, foreground, etc). 

I think it would be useful to be able to expose this information via `EventCounters`. Even if histogram functionality wasn't available, basic statistics like min/ average/ max/ count would be great.

**Comment by alexvaluyskiy** [comment]
I think, `.NET Runtime Metrics` should not be replaced by `EventCounters` in this repository, they both useful. For example, I could not use advanced metrics on production, because the metrics consume about 5-15% CPU for each service, so I use only `EventCounters` on production. But I use these metrics on performance environments and for debuggin purposes.
`EventCounters` could be easily implemented in your application, you could look at my example: https://github.com/alexvaluyskiy/prometheus-net-contrib

**Comment by djluck** [comment]
Closing this as V4 now uses event counters.
